package systemEinstellungen.abrechnung.formulare;

public interface TestInis {
    public static final String abrechnungini=""
            +"[Container]                                                                                   \n"
            +"StarteIn = 0                                                                                  \n"
            +"ImmerOptimieren = 1                                                                           \n"
            +"ZeigeAnPositionX = 0                                                                          \n"
            +"ZeigeAnPositionY = 0                                                                          \n"
            +"DimensionX = -1                                                                               \n"
            +"DimensionY = -1                                                                               \n"
            +"                                                                                              \n"
            +"[HMGKVRechnung]                                                                               \n"
            +"Rformular = HMRechnungGKV.ott                                                                 \n"
            +"Rdrucker = gkvdrucker                           \n"
            +"Tdrucker = taxdrucker                                          \n"
            +"Begleitzettel = HMBegleitzettelGKV.ott                                                        \n"
            +"Rauchdrucken = 1                                                                              \n"
            +"Rexemplare = 1                                                                                \n"
            +"FreigabeErzwingen = 1                                                                         \n"
            +";Rezept bekommt automatisch Haekchen wenn beim Abschliessen auch das 302-er Panel offen ist   \n"
            +"AutoOKwenn302offen = 0                                                                        \n"
            +";Groesse des Fensters fuer versch. Anz. Behandlungstage merken                                \n"
            +"keepTageTreeSize = 1                                                                          \n"
            +";maximale Anz. Behandlungstage                                                                \n"
            +"maxTage = 24                                                                                  \n"
            +";Aktualisieren der Eintraege gesperrt                                                         \n"
            +"lockSettings = 0                                                                              \n"
            +"usePrinterFromTemplate = 0                                                                    \n"
            +"TTS_10 = -234                                                                                 \n"
            +"                                                                                              \n"
            +"[HMPRIRechnung]                                                                               \n"
            +"Pformular = HMRechnungPrivat.ott                                                              \n"
            +"Pdrucker = privatdrucker                                               \n"
            +"Pexemplare = 2                                                                                \n"
            +"                                                                                              \n"
            +"[HMBGERechnung]                                                                               \n"
            +"Bformular = HMRechnungBG.ott                                                                  \n"
            +"Bdrucker = BGEDrucker                                                \n"
            +"Bexemplare = 4                                                                                \n"
            +"                                                                                              \n"
            +"[RehaGKVRechnung]                                                                             \n"
            +"RehaGKVformular = RehaRechnung.ott                                                            \n"
            +"RehaGKVdrucker = RICOH Aficio MP C2800 PS Farbe                                               \n"
            +"RehaGKVexemplare = 2                                                                          \n"
            +"RehaGKVik = 540840108                                                                         \n"
            +"                                                                                              \n"
            +"[RehaDRVRechnung]                                                                             \n"
            +"RehaDRVformular = RehaRechnung.ott                                                            \n"
            +"RehaDRVdrucker = RICOH Aficio MP C2800 PS Farbe                                               \n"
            +"RehaDRVexemplare = 2                                                                          \n"
            +"RehaDRVik = 510841109                                                                         \n"
            +"                                                                                              \n"
            +"[RehaPRIRechnung]                                                                             \n"
            +"RehaPRIformular = RehaRechnung.ott                                                            \n"
            +"RehaPRIdrucker = RICOH Aficio MP C2800 PS Farbe                                               \n"
            +"RehaPRIexemplare = 3                                                                          \n"
            +"RehaPRIik = 510841109                                                                         \n"
            +"                                                                                              \n"
            +"[GemeinsameParameter]                                                                         \n"
            +"InOfficeStarten = 1                                                                           \n"
            +"FragenVorEmail = 1                                                                            \n"
            +"                                                                                              \n"
            +"[GKVTaxierung]                                                                                \n"
            +"AnzahlVorlagen = 0                                                                            \n"
            +"Vorlage1 =                                                                                    \n"
            +"                                                                                              \n"
            +"[RGRParameter]                                                                                \n"
            +";Voreinstellung Bearbeitungsgeb�hr                                                            \n"
            +"RGRPauschale = 5,00                                                                           \n"
            +";Voreinstellung Anzahl Ausdrucke RGR-Rechnungen                                               \n"
            +"RGRexemplare = 2;";


}
